### ISSUE TITLE
Criação projeto electron

### ISSUE THREAD

**Issue by tissei** [CoolPodCast/playerDesktop#1]
### Dependências:
- Nenhuma.
### Tarefas:
- [x] Criar projeto electron com main process inicializando uma renderer em branco.
- [x] Adicionar gitignore para o electron.
- [x] Criar estruturas de pastas para scripts, assets e regras da aplicação.

**Comment by fabiorogeriosj** [comment]
Utilizado o [Electron Boilerplate](https://github.com/szwacz/electron-boilerplate) que já traz uma estrutura para:
- Testes unitários
- Testes de interface
- Script para build em release
- Ambiente de desenvolvimento separado
- Tarefas de conversão e compilação em Gulp
