### ISSUE TITLE
Criar logo projeto

### ISSUE THREAD

**Issue by fabiorogeriosj** [CoolPodCast/playerDesktop#10]
### Dependências:
- Nenhuma.
### Tarefas:
- [x] Criar logo e marca
  ![logo](https://cloud.githubusercontent.com/assets/1442874/18031212/5436cbb2-6cac-11e6-9d23-bf8c5956d311.png)
- [x] Criar paleta de cores

![paletacoolpodcast](https://cloud.githubusercontent.com/assets/1442874/18031078/0ca83804-6ca6-11e6-98a8-6547acf3be6b.png)

**Comment by fabiorogeriosj** [comment]
@leonardocadete, @tissei validar logo!

**Comment by tissei** [comment]
Não entendi como o cool e o podcastplayer se juntam na logo

**Comment by fabiorogeriosj** [comment]
![captura de tela 2016-08-31 as 19 44 44](https://cloud.githubusercontent.com/assets/1442874/18148959/6d9d90b8-6fb3-11e6-9be3-7004ad574904.png)

**Comment by tissei** [comment]
![6d9d90b8-6fb3-11e6-9be3-7004ad574904](https://cloud.githubusercontent.com/assets/4565640/18151381/35a6206e-6fc5-11e6-83a6-7110f00a8afa.png)

Testei com as ondas redondas ficou umas bosta, coloquei essas bordinhas ai pra diferenciar

**Comment by fabiorogeriosj** [comment]
Curti as bordinhas.
Em 31 de ago de 2016 9:53 PM, "José Carlos S.A. Tissei" <
notifications@github.com> escreveu:
