### ISSUE TITLE
Configurar projeto para Integração Contínua

### ISSUE THREAD

**Issue by fabiorogeriosj** [CoolPodCast/playerDesktop#11]
### Dependências:
- Nenhuma.
### Tarefas:
- [x] Instalar Travis CI para integração contínua seguindo guia oficial em [Electron](https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md)

**Comment by samiraguiar** [comment]
Done, Travis rodando testes unitários e e2e.
