### ISSUE TITLE
Liberar organização no waffle.io

### ISSUE THREAD

**Issue by tissei** [CoolPodCast/playerDesktop#4]
@fabiorogeriosj 
### Dependências:
- Nenhuma.
### Tarefas:
- [x] Liberar organização e repositório no waffle.io.
- [x] Verificar se as issues existentes são exibidas corretamente no waffle.
- [x] Realizar ajustes se necessários para exibição das issues.

**Comment by fabiorogeriosj** [comment]
Acesso em: https://waffle.io/CoolPodCast/playerDesktop
