### ISSUE TITLE
Configurar typings no projeto

### ISSUE THREAD

**Issue by tissei** [CoolPodCast/playerDesktop#5]
### Dependências:
#2
### Tarefas:
- [ ] Configurar o [typescript typings](https://github.com/typings/typings) no projeto através do bower.
- [ ] Adicionar gitignore para o typings.
- [ ] Adicionar typings para Angular, Angular Static e JQuery.

**Comment by fabiorogeriosj** [comment]
@tissei  Vamos usar typescript? Na estrutura que esta podemos desenvolver com as features do ES6.
